### ISSUE TITLE
mk command breaks in node v6

### ISSUE THREAD

**Issue by jtenner** [egoist/node-make#5]
```
PS C:\Users\jtenner\desktop\projects\sidekick-worker> mk
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:697:5)
    at C:\Users\jtenner\AppData\Roaming\npm\node_modules\mkfile\node_modules\babel-core\lib\transformation\file\options\
option-manager.js:353:36
    at C:\Users\jtenner\AppData\Roaming\npm\node_modules\mkfile\node_modules\babel-core\lib\transformation\file\options\
option-manager.js:375:22
    at Array.map (native)
    at OptionManager.resolvePresets (C:\Users\jtenner\AppData\Roaming\npm\node_modules\mkfile\node_modules\babel-core\li
b\transformation\file\options\option-manager.js:364:20)
    at OptionManager.mergePresets (C:\Users\jtenner\AppData\Roaming\npm\node_modules\mkfile\node_modules\babel-core\lib\
transformation\file\options\option-manager.js:348:10)
    at OptionManager.mergeOptions (C:\Users\jtenner\AppData\Roaming\npm\node_modules\mkfile\node_modules\babel-core\lib\
transformation\file\options\option-manager.js:307:14)
    at OptionManager.init (C:\Users\jtenner\AppData\Roaming\npm\node_modules\mkfile\node_modules\babel-core\lib\transfor
mation\file\options\option-manager.js:465:10)
    at File.initOptions (C:\Users\jtenner\AppData\Roaming\npm\node_modules\mkfile\node_modules\babel-core\lib\transforma
tion\file\index.js:194:75)
```

I just switched to node.js v6, is there something wrong with the package?

**Comment by egoist** [comment]
Yep, it's caused by the node v6, https://github.com/floatdrop/require-from-string/pull/5

upgrade to mkfile `v1.2.0` should fix this.

**Comment by jtenner** [comment]
Thanks. It's fixed! Wonderful project!

**Comment by egoist** [comment]
@jtenner Glad to hear that 😃 cheers 🍻
